#!/usr/bin/env python

"""
Openshift WSGI application
"""

import os
import sys

# add local code
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR']))

# initialise virtual environment
virtenv = os.environ['OPENSHIFT_HOMEDIR'] + 'python-2.7/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')

virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# import and configure WSGI application

from webapp import app as application
