"""empty message

Revision ID: 3d0bb1f1737b
Revises: None
Create Date: 2013-12-23 21:14:11.050001

"""

# revision identifiers, used by Alembic.
revision = '3d0bb1f1737b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
