"""empty message

Revision ID: 431854ffa488
Revises: 3d0bb1f1737b
Create Date: 2013-12-23 22:13:24.637899

"""

# revision identifiers, used by Alembic.
revision = '431854ffa488'
down_revision = '3d0bb1f1737b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=True))

    try:
        op.create_unique_constraint(None, 'users', ['email'])
    except NotImplementedError:
        pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'users')
    except NotImplementedError:
        pass
    op.drop_column('users', 'email')
    ### end Alembic commands ###
